### ISSUE TITLE
DetectionSuite with Caffe

### ISSUE THREAD

**Issue by DavidButra** [JdeRobot/DetectionSuite#138]
Hi,

I am working on deep learning using the framework caffe. To test trained networks, I would like to use Detection Suite. I have installed it as it says in the guide, setting up OpenCV 3.4 to use Caffe but when I run the DatasetEvaluationApp script I don't see Caffe in the possible inferencing frameworks.

Does anyone know what the reason for this could be?

Thanks!

**Comment by vinay0410** [comment]
Hi @DavidButra ,
Thanks for reporting this. There was a critical bug in root level CMakeLists.txt.
Just take a fresh pull, and you should see caffe as a valid list of inferencers.

**Comment by DavidButra** [comment]
It works!

Now, I can see caffe as a valid inferencer.

Thank so much @vinay0410
