### ISSUE TITLE
DatasetEvaluationApp | Caffe - Error starting camera

### ISSUE THREAD

**Issue by DavidButra** [JdeRobot/DetectionSuite#139]
Hi!

I found a problem when I tried to run DatasetEvaluationApp script. I am working with Caffe and I wanted to use my laptop cam to detect the objects captured but, after starting the app, when I pressed Process button to see the camera, the following error showed up:

------------------------------------------------------------------
I0424 22:28:17.004871  2895 Utils.cpp:91] 0
I0424 22:28:17.004951  2895 CameraReader.cpp:4] Starting Capture from device with DeviceId: 0
I0424 22:28:17.414113  2895 FrameworkInferencer.cpp:35] Mean inference time: 0(ms)
I0424 22:28:17.414162  2895 CameraReader.cpp:14] Releasing Camera
E0424 22:28:17.415625  2895 mainwindow.cpp:504] Exception Detected: stof
------------------------------------------------------------------

Later, I tried the app using a saved video but the result was the same.

Could this problem be related to the inferencer used? If not, would you know the reason for this problem?

Thanks!

**Comment by vinay0410** [comment]
Hi @DavidButra ,
This is a problem relating to the inferencer you are using, Could you send the weights and config file of the inferencer you are using.

Also, a list of supported inferencers is present [here](https://github.com/JdeRobot/DetectionSuite/wiki/Model-Zoo)

In the meantime you can test the following Caffe inferencer:

Weights File: https://drive.google.com/open?id=0B3gersZ2cHIxZi13UWF0OXBsZzA
Config File: https://drive.google.com/file/d/1hO233qK0FvLL9MQSFViRRfJC7tvVi1Hk/view?usp=sharing
Class name File: https://github.com/JdeRobot/DetectionSuite/wiki/voc.names

I have tested the above with the following inferencer params:
![Inferencer params](https://user-images.githubusercontent.com/18044818/56710524-4126a700-6744-11e9-978d-0ca3664183de.png)

**Comment by DavidButra** [comment]
Hi @vinay0410,

I found my error. It was because of parameters I was using. But now, introducing a correct inferencer, the following error shows up.

------------------------------------------------------------------
I0427 17:04:56.104221  3216 Utils.cpp:91] 0
I0427 17:04:56.237280  3216 MassInferencer.cpp:101] Evaluating : 1(1/0)
OpenCV Error: Assertion failed (blobs.size() != 0) in getMemoryShapes, file /home/davidbutra/opencv/modules/dnn/src/layers/convolution_layer.cpp, line 253
I0427 17:04:56.265655  3216 FrameworkInferencer.cpp:35] Mean inference time: 0(ms)
I0427 17:04:56.265722  3216 VideoReader.cpp:17] Releasing Video File
E0427 17:04:56.269784  3216 mainwindow.cpp:504] Exception Detected: /home/davidbutra/opencv/modules/dnn/src/layers/convolution_layer.cpp:253: error: (-215) blobs.size() != 0 in function getMemoryShapes
------------------------------------------------------------------
 
Do you know what the problem is?

Thanks!

**Comment by vinay0410** [comment]
Hi @DavidButra ,
This error is probably occuring due to the use of incorrect weights file or incorrect config file.
Did you try the combination, of weights, config and parameters I mentioned in my previous comment.

**Comment by DavidButra** [comment]
Hi @vinay0410,

I tried the app using the combination, of weights, config and parameters you mentioned, but the error persists.

![Área de trabajo 1_001](https://user-images.githubusercontent.com/18295154/56918421-41190500-6abe-11e9-8283-9adbf91fdfcd.png)

**Comment by DavidButra** [comment]
Hello @vinay0410,

Do you know something new about this issue?

Thanks!

**Comment by vinay0410** [comment]
I have tested it on my machine, and it works fine. Could you share a small screen recording of using caffe.
It’s probably a usage issue. I just want to see, how you are running it.

**Comment by DavidButra** [comment]
Hi @vinay0410,

I share a screen recording of how I am trying the app using Caffe [1]. I also attach a image with opencv version I am using.

[1] https://www.youtube.com/watch?v=zZM9mOAi5y8&feature=youtu.be

![Selección_002](https://user-images.githubusercontent.com/18295154/57155606-37eca880-6ddc-11e9-806e-c2185717b713.png)

**Comment by vinay0410** [comment]
Okay, I will try again to replicate this error using the opencv version you mentioned.

**Comment by vinay0410** [comment]
Hi @DavidButra ,
It was my mistake, the weight and config files I gave you were incompatible.
Please find attached new weights and config files.
Also, don't select RGB, because this model is trained on BGR images.

Weights File: https://drive.google.com/open?id=1G9l_X1UwlyhaSBHRcXes5GjydVzZ7sWC
Config File: https://drive.google.com/open?id=1b97yKuv2_D_JrLOzaDPQTkJdFDWImqzF
Class Names File: Same as before

I have tested them with both OpenCV 3.4 and 4.0

**Comment by DavidButra** [comment]
Hi @vinay0410,

it works! Now, the camera shows up. But, there seems to be a problem because inside the Detection window, no object is detected, showing only the captured images.

The output of the application is something like that:

<img width="566" alt="Terminal" src="https://user-images.githubusercontent.com/18295154/57329320-d1d18f80-7113-11e9-8908-0e60e011a1a4.png">

What could be the problem?

Thanks!

**Comment by vinay0410** [comment]
Hi @DavidButra ,
I have tested these inferencers again on my end.
And they are detecting objects.
![Screenshot from 2019-05-13 10-25-31](https://user-images.githubusercontent.com/18044818/57596685-9991dd00-7569-11e9-99f0-fe84764dde40.png)

I see that there are no detections on your side. Try switching the Use RGB checkbox, and decreasing the confidence threshold.

Also, make sure that you are pointing to objects listed in voc.names. It will only detect those 20 objects.

If you are still facing issues, then just post a screen shot of your detection window, just like I did.

**Comment by DavidButra** [comment]
Hi @vinay0410,

I tried the app using RGB checkbox and decreasing the confidence threshold until almost the minimum (0.05).

![Área de trabajo 1_004](https://user-images.githubusercontent.com/18295154/57778477-6f384f00-7724-11e9-9e1e-a69a44f5c095.png)

I tried recording a tv monitor like you did but the application still didn't detect any objects. 

![Área de trabajo 1_006](https://user-images.githubusercontent.com/18295154/57778755-ff769400-7724-11e9-80d5-d13b3710ea35.png)

**Comment by sleep-404** [comment]
![app](https://user-images.githubusercontent.com/31350263/57827072-94c86580-77c3-11e9-926c-c508c84e396a.png)
![caffe](https://user-images.githubusercontent.com/31350263/57827090-a873cc00-77c3-11e9-86bc-7a8a4f8b811b.png)
![result](https://user-images.githubusercontent.com/31350263/57827192-13bd9e00-77c4-11e9-8d14-b455e0bd03ba.png)

**Comment by sleep-404** [comment]
![app](https://user-images.githubusercontent.com/31350263/57827675-d528e300-77c5-11e9-9244-3cc0c2f4af53.png)

![caffe](https://user-images.githubusercontent.com/31350263/57827572-7499a600-77c5-11e9-91fc-d270e639a789.png)
![result](https://user-images.githubusercontent.com/31350263/57827573-75323c80-77c5-11e9-980d-b34c07625b39.png)

**Comment by DavidButra** [comment]
Hi @vinay0410,

I've just installed Caffe and JdeRobot in a new pc from scratch, but the problem persists, because the application still doesn't detect any objects.

I am using VirtualBox with Ubuntu 16.04 and I have installed Caffe using CPU-only mode. Could this have anything to do with it?

Thank you again.

**Comment by DavidButra** [comment]
Hi @vinay0410,

I tried the app using a pretrained SSD model and it works correctly. Maybe, there is something wrong in the models I was using.

![DetectionSuite_1](https://user-images.githubusercontent.com/18295154/58749426-4931df00-8486-11e9-85c9-70cce8a67cb4.png)

![DetectionSuite_2](https://user-images.githubusercontent.com/18295154/58749428-4cc56600-8486-11e9-86b3-898762658adf.png)

Regards!

**Comment by jmplaza** [comment]
Good news @DavidButra, glad to know it works now on your machine. Well done @vinay0410 !
