### ISSUE TITLE
Gtk-ERROR ** Using GTK+ 2.x and GTK+ 3 in the same process

### ISSUE THREAD

**Issue by sleep-404** [JdeRobot/DetectionSuite#140]
When trying to run the app the following error pops up. As it states , I think multiple versions are being linked.
![err1](https://user-images.githubusercontent.com/31350263/57425756-2838ee00-723a-11e9-9878-465f3fd31107.png)
Currently am trying to remove one version (gtk3) to try fixing the error.
Reference : https://ubuntuforums.org/showthread.php?t=1841557

**Comment by sleep-404** [comment]
and it definitely was a bad idea i guess !

**Comment by vinay0410** [comment]
I have also faced this error, and is generally because of conflicting versions of gtk in opencv and DetectionSuite.

I fixed it by reinstalling opencv with this altered cmake command

cmake -D WITH_QT=ON -D WITH_GTK=OFF ..
