### ISSUE TITLE
Integrate changes made during GSoC 19

### ISSUE THREAD

**Issue by sergiopaniego** [JdeRobot/DetectionSuite#146]
Integrate in the main repository and add to the master branch the improvements done by @sleep-404 during GSoC 19 from the [repository](https://github.com/TheRoboticsClub/colab-gsoc2019-Jeevan_Kumar) created during the summer

**Comment by vinay0410** [comment]
@sleep-404, can you open all the necessary pull requests.
I see only two PRs.

**Comment by sleep-404** [comment]
Actually , I have a few suggestions , so was waiting to do it after today's meeting

**Comment by sleep-404** [comment]
on it !

**Comment by sergiopaniego** [comment]
I have been working on this part and I have created a new [branch](https://github.com/JdeRobot/DetectionSuite/tree/gsoc_2019) with the changes. I am currently testing if everything works as expected, so we can work in that branch I guess. I have just added the work done by @sleep-404, without adding any new idea or modification.
