### ISSUE TITLE
Remove Python Build Files

### ISSUE THREAD

**Issue by hogum** [JdeRobot/DetectionSuite#179]
The repository contains pushed `.pyc` files [in this](https://github.com/JdeRobot/DetectionSuite/tree/master/sampleGenerator/simpleSampleGenerator/sampleGenerator) directory. I'd be willing to make a commit that deletes them.
From [this](https://github.com/JdeRobot/DetectionSuite/commit/26f6c7d8cf64798ddf615f9441ab1bf27b48c8a2) previous commit, a similar binary file has been pushed, but was noted, before - this is just a question, would specifying them in a `gitignore` file help?

**Comment by sergiopaniego** [comment]
Thanks for your comment! 😃 
You're completely right, those `.pyc` should be removed and add them in a `.gitignore `so they are not uploaded anymore. 

Could you open a pull request with the changes? 👍

**Comment by hogum** [comment]
Sure. I'll create a pull request

**Comment by sergiopaniego** [comment]
Thanks for your collaboration!
